In [ ]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [ ]:
class Neuron:
  def __init__(self, weights, bias):
    # <создать атрибуты объекта weights и bias>
    self.weights = weights
    self.bias = bias
  
  def forward(self, inputs):
    # <реализовать логику нейрона>
    return torch.dot(inputs, self.weights).sum() + self.bias


In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

In [ ]:
my_neuron = Neuron(weights, bias)
my_neuron.forward(inputs)

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат. 

In [ ]:
class Linear:
  def __init__(self, weights, biases):
    # <создать атрибуты объекта weights и biases>
    self.weights = weights
    self.biases = biases    
  
  def forward(self, inputs):
    # <реализовать логику слоя>
    return torch.matmul(inputs, self.weights) + self.biases

In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T
biases = torch.tensor([3.14, 2.71, 7.2])

In [ ]:
torch.matmul(inputs, weights)

tensor([ 1.7000, -2.5400,  3.1900])

In [ ]:
lin_neuron = Linear(weights, biases)
lin_neuron.forward(inputs)

tensor([ 4.8400,  0.1700, 10.3900])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [ ]:
class Linear:
  def __init__(self, weights, biases):
    # <создать атрибуты объекта weights и biases>
    self.weights = weights
    self.biases = biases    
  
  def forward(self, inputs):
    # <реализовать логику слоя>
    return torch.matmul(inputs, self.weights) + self.biases

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [ ]:
lin_neuron = Linear(weights, biases)
lin_neuron.forward(inputs)

tensor([[ 3.7900,  0.9200,  9.0850],
        [ 6.1400, -2.1000,  6.9000],
        [ 2.0400,  0.7610,  6.7260]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    self.weights = torch.randn(n_features, n_neurons)
    self.biases = torch.zeros(n_neurons)    
  
  def forward(self, inputs):
    # <реализовать логику слоя>
    return torch.matmul(inputs, self.weights) + self.biases

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

linear = Linear(n_features = 4, n_neurons = 3)
linear.forward(inputs)

tensor([[-5.6897, -5.2130, -1.7040],
        [ 7.0606, -4.3409,  5.2954],
        [-4.0935, -7.0265,  4.4285]])

2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

linear_1 = Linear(n_features = 4, n_neurons = 3)
linear_2 = Linear(n_features = 3, n_neurons = 7)
outs1 = linear_1.forward(inputs)
outs2 = linear_2.forward(outs1)
outs2

tensor([[-4.8435e-01,  4.7903e+00,  4.6006e+00, -5.6316e+00, -2.1731e+00,
         -1.3729e+00,  7.7546e+00],
        [-5.0718e+00,  1.9435e+00, -1.3836e+01,  6.7717e+00,  6.9530e+00,
          1.5972e+01, -3.1531e+00],
        [-1.3095e-01, -5.8354e-03, -2.1411e+00,  1.3036e+00,  7.8872e-01,
          2.0645e+00, -5.5715e-01]])

In [ ]:
linear_1.biases, linear_1.weights, outs1, linear_2.biases, linear_2.weights, outs2

(tensor([0., 0., 0.]), tensor([[-1.9928, -1.4443,  1.1424],
         [ 0.0441,  0.2870,  0.5159],
         [-0.8369,  0.1171,  0.9405],
         [-1.1247, -0.6770, -0.1321]]), tensor([[-7.2271, -2.2115,  4.6654],
         [-5.1776, -2.9245,  3.6597],
         [ 1.2465,  3.8694,  2.8885]]), tensor([0., 0., 0., 0., 0., 0., 0.]), tensor([[-0.0078, -0.4810,  1.7825, -0.7949, -2.4141, -0.1699,  2.0147],
         [-0.5051, -1.1403, -0.0978, -0.4590, -2.5304,  0.6930,  0.5222],
         [ 0.2094, -1.1392, -0.2885,  1.8018, -0.5235, -2.1882,  0.4798]]), tensor([[  2.1500,   0.6831, -14.0124,  15.1662,  20.6007, -10.5133, -13.4766],
         [  2.2837,   1.6561,  -9.9992,  12.0521,  17.9836,  -9.1549, -10.2023],
         [ -1.3593,  -8.3024,   1.0103,   2.4378, -14.3125,  -3.8511,   5.9177]]))

In [ ]:
# получить матрицу 4*6
# 4*3 * 3*3= 4*3 * 3*6 = 4*6

In [ ]:
inputs = inputs.T
linear_1 = Linear(n_features = 3, n_neurons = 3)
linear_2 = Linear(n_features = 3, n_neurons = 6)
outs1 = linear_1.forward(inputs)
outs2 = linear_2.forward(outs1)
outs1, outs2

(tensor([[ -3.1390,  -1.5427,  -1.7559],
         [-13.5502,   6.8016, -14.9879],
         [ -6.8784,   7.9821,  -4.9464],
         [ -6.3612,   0.8737,  -3.5931]]),
 tensor([[  5.3171,  -3.0062,   4.1929,  -5.4196,  -1.4758,   0.8733],
         [ 47.8256, -50.7850,  22.8687, -11.0567,   2.3485,  13.4827],
         [ 28.6504, -28.7256,   8.0045,   7.1356,   3.6923,   8.7480],
         [ 16.4864, -13.2178,   7.7246,  -3.7029,  -0.5820,   4.0824]]))

## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [ ]:
class ReLU:
  def forward(self, inputs):
    # <реализовать логику ReLU>
    inputs[inputs<0] = 0
    return inputs

In [ ]:
inputs = torch.randn(4, 3)
print(inputs) 
ReLU().forward(inputs)

tensor([[-0.5714, -0.7370,  1.8905],
        [-0.1998,  2.0304, -0.1296],
        [ 1.1590,  0.1874, -1.0878],
        [-0.2569,  0.7427, -0.0921]])


tensor([[0.0000, 0.0000, 1.8905],
        [0.0000, 2.0304, 0.0000],
        [1.1590, 0.1874, 0.0000],
        [0.0000, 0.7427, 0.0000]])

2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [ ]:
class Softmax:
  def forward(self, inputs):
    # <реализовать логику Softmax>
    return torch.exp(inputs) / torch.exp(inputs).sum(1).view(-1, 1)  

In [ ]:
inputs = torch.randn(4, 3)
print(inputs)
Softmax().forward(inputs)

tensor([[-2.9549,  1.0250,  0.7244],
        [-1.7809, -1.5076, -0.5768],
        [-0.0043,  0.7930, -2.1991],
        [ 1.0548, -0.7455, -1.2421]])


tensor([[0.0106, 0.5685, 0.4209],
        [0.1770, 0.2327, 0.5903],
        [0.3002, 0.6664, 0.0334],
        [0.7900, 0.1306, 0.0794]])

2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [ ]:
class ELU:
  def __init__(self, alpha=1):
    # <создать атрибут объекта alpha>
    self.alpha = alpha

  def forward(self, inputs):
    # <реализовать логику ReLU>
    inputs[inputs<0] = self.alpha * (torch.exp(inputs[inputs<0]) - 1)
    return inputs

In [ ]:
inputs = torch.randn(4, 3)
print(inputs)
ELU().forward(inputs)

tensor([[-0.8220, -1.1421,  0.4565],
        [ 0.4525, -0.2106, -0.6334],
        [-2.1573, -0.4335,  0.9761],
        [ 1.5292, -1.5153, -0.7994]])


tensor([[-0.5605, -0.6809,  0.4565],
        [ 0.4525, -0.1899, -0.4692],
        [-0.8844, -0.3517,  0.9761],
        [ 1.5292, -0.7803, -0.5504]])

## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    # <реализовать логику MSE>
    return 1 / y_pred.size()[0] * ((y_true - y_pred)**2).sum()

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

In [ ]:
y_pred = Linear(n_features=4, n_neurons=1).forward(inputs)
y_pred, MSELoss().forward(y_pred, y)

(tensor([[-11.5559],
         [ -5.0041],
         [ -8.2320]]), tensor(404.0987))

2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [ ]:
# НЕПРАВИЛЬНО!!! убрать 1 из сум - должно же быть одно число (меня смутило суммирование по j?)
class CategoricalCrossentropyLoss:
  def forward(self, y_pred, y_true):
    # <реализовать логику CCE>
    return -1 * (y_true * y_pred.log()).sum()

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                        [2, 5, -1, 2], 
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

In [ ]:
y_pred = Linear(n_features=4, n_neurons=3).forward(inputs)
CategoricalCrossentropyLoss().forward(Softmax().forward(y_pred) , y)

tensor(0.1964)

2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [ ]:
# class MSELossL2:
#   def __init__(self, lambda_):
#     # <создать атрибут объекта alpha>
#     self.alpha = lambda_

#   def data_loss(self, y_pred, y_true):
#     # <подсчет первого слагаемого из формулы>
#     return ((y_true - y_pred)**2).sum()

#   def reg_loss(self, layer):
#     # используйте атрибуты объекта layer, в которых хранятся веса слоя
#     # <подсчет второго слагаемого из формулы>
#     return self.alpha * (layer.weights**2).sum()

#   def forward(self, y_pred, y_true):
#     return self.data_loss(y_pred, y_true) + self.reg_loss(y_pred, y_true)

In [ ]:
# a - weights
class MSELossL2:
  def __init__(self, lambda_, layer):
    # <создать атрибут объекта alpha>
    self.alpha = lambda_
    self.layer = layer

  def data_loss(self, y_pred, y_true):
    # <подсчет первого слагаемого из формулы>
    return ((y_true - y_pred)**2).sum()

  def reg_loss(self, layer):
    # используйте атрибуты объекта layer, в которых хранятся веса слоя
    # <подсчет второго слагаемого из формулы>
    return self.alpha * (layer.weights**2).sum()

  def forward(self, y_pred, y_true):
    return self.data_loss(y_pred, y_true) + self.reg_loss(self.layer)

In [ ]:
layer = Linear(n_features=4, n_neurons=3)
y_pred, MSELossL2(lambda_=1, layer=layer).forward(layer.forward(inputs), y)

(tensor([[-5.1654,  1.5482, -1.2737],
         [-7.9207,  8.8930,  1.3222],
         [-0.9662, -3.1817, -5.2910]]), tensor(261.5272))

## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [ ]:
import numpy as np
#генерация датасета для задачи регрессии
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5)
X = torch.from_numpy(X).to(dtype=torch.float32)
y = torch.from_numpy(y).to(dtype=torch.float32)

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [ ]:
class SquaredLoss:
    def forward(self, y_pred, y_true):
      return ((y_pred - y_true) ** 2).mean() # <реализовать логику MSE> - функция потерь

    def backward(self, y_pred, y_true):
      self.dinput = 2 * (y_pred - y_true).mean() # df/dc - dvalue
      return self.dinput

2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [ ]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    self.n_inputs = n_inputs
    self.weights = torch.randn(n_inputs)
    self.bias = torch.randn(1)
  
  def forward(self, input):
    # <реализовать логику нейрона>
    self.input = input
    return torch.dot(self.weights, input) + self.bias
  
  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    self.dweights = dvalue * self.input # df/dW     de/dt*X
    self.dinput =  dvalue * self.weights # df/wX    de/dt*W
    self.dbias = dvalue # df/db                     de/dt*1

2.4.1.3 Допишите цикл для настройки весов нейрона

стохастический градиентный спуск

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [ ]:
n_inputs = 4 # <размерность элемента выборки >
lr = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = SquaredLoss()

losses = []
for epoch in range(100):
  for x_example, y_example in zip(X, y):
    # forward pass
    y_pred = neuron.forward(x_example) # <прогон через нейрон>
    curr_loss = loss.forward(y_pred, y_example) # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    loss.backward(y_pred, y_example)
    neuron.backward(loss.dinput)

    # update weights
    neuron.weights -= lr * neuron.dweights
    neuron.bias -= lr * neuron.dbias

  print(f'epoch {epoch} mean loss {sum(losses) / len(losses)}')
    
    
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу
    # <шаг оптимизации для весов (weights и bias) нейрона>

epoch 0 mean loss 860.463623046875
epoch 1 mean loss 430.2318115234375
epoch 2 mean loss 286.8211975097656
epoch 3 mean loss 215.11590576171875
epoch 4 mean loss 172.09271240234375
epoch 5 mean loss 143.4105987548828
epoch 6 mean loss 122.92337036132812
epoch 7 mean loss 107.55795288085938
epoch 8 mean loss 95.60706329345703
epoch 9 mean loss 86.04635620117188
epoch 10 mean loss 78.22396087646484
epoch 11 mean loss 71.7052993774414
epoch 12 mean loss 66.18950653076172
epoch 13 mean loss 61.46168518066406
epoch 14 mean loss 57.36423873901367
epoch 15 mean loss 53.77897644042969
epoch 16 mean loss 50.61550521850586
epoch 17 mean loss 47.803531646728516
epoch 18 mean loss 45.28755569458008
epoch 19 mean loss 43.02317810058594
epoch 20 mean loss 40.974456787109375
epoch 21 mean loss 39.11198043823242
epoch 22 mean loss 37.411460876464844
epoch 23 mean loss 35.8526496887207
epoch 24 mean loss 34.41854476928711
epoch 25 mean loss 33.09475326538086
epoch 26 mean loss 31.869022369384766
epoch 

In [ ]:
# TODO: берем рандомную часть выборки, каждый раз разная; 
# считать ошибку не на всем датасете а только на рандомной части
# batch - рандомная часть выборки

n_inputs = 4 # <размерность элемента выборки >
lr = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох
batch_size = 15

neuron = Neuron(n_inputs)
loss = SquaredLoss()

losses = []
for epoch in range(100):
  sample = torch.randint(0, X.shape[0], size=(batch_size,)) # берем рандомные индексы
  for x_example, y_example in zip(X[sample], y[sample]):
    # forward pass
    y_pred = neuron.forward(x_example) # <прогон через нейрон>
    curr_loss = loss.forward(y_pred, y_example) # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    loss.backward(y_pred, y_example)
    neuron.backward(loss.dinput)

    # update weights
    neuron.weights -= lr * neuron.dweights
    neuron.bias -= lr * neuron.dbias

  print(f'epoch {epoch} mean loss {np.mean(losses)}')

epoch 0 mean loss 3178.654541015625
epoch 1 mean loss 1782.4659423828125
epoch 2 mean loss 1194.2769775390625
epoch 3 mean loss 895.7516479492188
epoch 4 mean loss 716.60986328125
epoch 5 mean loss 597.1755981445312
epoch 6 mean loss 511.86480712890625
epoch 7 mean loss 447.8817138671875
epoch 8 mean loss 398.1170654296875
epoch 9 mean loss 358.30535888671875
epoch 10 mean loss 325.7321472167969
epoch 11 mean loss 298.58782958984375
epoch 12 mean loss 275.6195068359375
epoch 13 mean loss 255.93240356445312
epoch 14 mean loss 238.8702392578125
epoch 15 mean loss 223.94085693359375
epoch 16 mean loss 210.7678680419922
epoch 17 mean loss 199.05853271484375
epoch 18 mean loss 188.58177185058594
epoch 19 mean loss 179.15267944335938
epoch 20 mean loss 170.62159729003906
epoch 21 mean loss 162.86607360839844
epoch 22 mean loss 155.78494262695312
epoch 23 mean loss 149.29391479492188
epoch 24 mean loss 143.32215881347656
epoch 25 mean loss 137.80975341796875
epoch 26 mean loss 132.70568847656