# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## не использовать циклы!!!

In [2]:
import numpy as np

lst = [1, 2, 3, 4, 5, 6]
arr = np.array(lst)
print(arr ** 2) # - векторизованная операция, сила numpy, не нужны циклы
lst ** 2 

[ 1  4  9 16 25 36]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [23]:
mask = arr >= 3
print(mask)
arr[mask]

[False False  True  True  True  True]


array([3, 4, 5, 6])

In [24]:
arr = np.arange(20).reshape(5, -1) #-1, чтобы последнюю ось не задавать
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

xi = (xi - min(x)) / (max(x) - min(x))

In [31]:
arr_ = np.random.uniform(0, 20, (4, 7))
(arr_ - np.min(arr_)) / (np.max(arr_) - np.min(arr_))

array([[0.5904639 , 0.14994211, 0.37323302, 0.68794006, 0.25431974,
        0.25715671, 0.55847133],
       [0.19264274, 0.92007965, 0.66537409, 0.06212184, 0.55898815,
        0.86506292, 0.01998741],
       [0.15245776, 0.28451635, 0.27945581, 0.94852037, 1.        ,
        0.94988503, 0.64545816],
       [0.47444287, 0.65686601, 0.        , 0.94581505, 0.60256618,
        0.87029307, 0.24627633]])

In [32]:
# к виду 
a = 1 / (arr_.max() - arr_.min())
b = -arr_.min() / (arr_.max() - arr_.min())
a * arr_ + b

array([[0.5904639 , 0.14994211, 0.37323302, 0.68794006, 0.25431974,
        0.25715671, 0.55847133],
       [0.19264274, 0.92007965, 0.66537409, 0.06212184, 0.55898815,
        0.86506292, 0.01998741],
       [0.15245776, 0.28451635, 0.27945581, 0.94852037, 1.        ,
        0.94988503, 0.64545816],
       [0.47444287, 0.65686601, 0.        , 0.94581505, 0.60256618,
        0.87029307, 0.24627633]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [33]:
arr = np.random.randint(0, 10, (8, 10))
arr

array([[6, 2, 2, 9, 3, 5, 3, 2, 2, 6],
       [5, 1, 3, 8, 9, 6, 1, 4, 1, 0],
       [2, 6, 7, 9, 7, 9, 2, 7, 7, 7],
       [5, 1, 5, 1, 5, 4, 3, 5, 0, 3],
       [0, 4, 6, 7, 7, 3, 4, 8, 8, 8],
       [6, 2, 4, 1, 5, 3, 9, 5, 6, 6],
       [3, 2, 6, 1, 4, 1, 2, 3, 5, 5],
       [0, 2, 7, 4, 2, 9, 2, 0, 9, 5]])

In [41]:
arr.sum(axis=1)

array([40, 38, 63, 32, 55, 47, 32, 40])

In [40]:
#1 var
mask = arr.sum(axis=1) == arr.sum(axis=1).min()
print(mask)
arr[mask]

[False False False  True False False  True False]


array([[5, 1, 5, 1, 5, 4, 3, 5, 0, 3],
       [3, 2, 6, 1, 4, 1, 2, 3, 5, 5]])

In [42]:
#2 var
min_index = np.argmin(arr.sum(axis=1))
print(min_index)
arr[min_index, :]

3


array([5, 1, 5, 1, 5, 4, 3, 5, 0, 3])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [47]:
a = np.random.randint(0, 10, 5)
print(a)
b = np.random.randint(0, 10, 5)
print(b)

[4 3 2 3 9]
[5 3 7 1 2]


In [48]:
(np.sum((a - b) ** 2)) ** (1/2)

8.888194417315589

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [58]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
data = np.loadtxt("./minutes_n_ingredients.csv", dtype = int, delimiter = ",", skiprows = 1)
data[0:5] 

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
print("среднее -> ", np.mean(data[:, 1:], axis = 0))
print("минимум -> ", np.min(data[:, 1:], axis = 0))
print("максимум -> ", np.max(data[:, 1:], axis = 0))
print("медиана -> ", np.median(data[:, 1:], axis = 0))

среднее ->  [2.16010017e+04 9.05528000e+00]
минимум ->  [0 1]
максимум ->  [2147483647         39]
медиана ->  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [14]:
# отсеить рецепты, продолжительность выполнения которых больше чем квантиль?
q = np.quantile(data[:, 1], 0.75)
mask = data[:, 1] <= q
data[mask]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [44]:
mask = data[:, 1] == 0 
print(len(data[mask]))
data4 = data.copy()
data4[mask, 1] = 1
mask4 = data4[:, 1] == 0 
print(len(data4[mask4]))

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [37]:
len(np.unique(data[:,0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [43]:
print(len(np.unique(data[:,2])))
unic, n = np.unique(data[:,2], return_counts = True)
dict(zip(unic, n))

37


{1: 13,
 2: 926,
 3: 2895,
 4: 5515,
 5: 7913,
 6: 9376,
 7: 10628,
 8: 10951,
 9: 10585,
 10: 9591,
 11: 8297,
 12: 6605,
 13: 4997,
 14: 3663,
 15: 2595,
 16: 1767,
 17: 1246,
 18: 790,
 19: 573,
 20: 376,
 21: 217,
 22: 161,
 23: 105,
 24: 69,
 25: 50,
 26: 28,
 27: 16,
 28: 16,
 29: 12,
 30: 12,
 31: 3,
 32: 1,
 33: 2,
 34: 1,
 35: 3,
 37: 1,
 39: 1}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [50]:
mask = data[:, 2] <= 5
#print(data)
data7 = data.copy()
data7 = data7[mask] 
#print(data7)
print(len(data),len(data7))

100000 17262


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [60]:
t8 = data4[:,2]/data4[:,1]
print(np.max(t8))
dict(zip(data4[:,0], t8))

24.0


{127244: 0.26666666666666666,
 23891: 0.28,
 94746: 0.6,
 67660: 1.2,
 157911: 0.23333333333333334,
 152828: 0.175,
 33941: 0.5,
 446597: 0.3333333333333333,
 366174: 1.2857142857142858,
 74205: 0.35,
 504666: 0.3076923076923077,
 81006: 0.5833333333333334,
 280968: 0.12941176470588237,
 204134: 0.6,
 18593: 0.2,
 25623: 0.6666666666666666,
 65559: 0.5833333333333334,
 99836: 0.03888888888888889,
 87775: 0.1625,
 425704: 0.3,
 101799: 0.8,
 106325: 0.15714285714285714,
 99283: 0.01904761904761905,
 179504: 0.07333333333333333,
 276123: 0.11666666666666667,
 498382: 0.21176470588235294,
 197140: 0.15,
 484223: 0.2222222222222222,
 385472: 0.1,
 63150: 0.016,
 378114: 0.55,
 318295: 0.05384615384615385,
 259784: 0.1,
 308301: 0.09166666666666666,
 422795: 0.23333333333333334,
 104773: 0.07333333333333333,
 114103: 0.01981981981981982,
 496430: 0.25,
 160325: 0.15555555555555556,
 328135: 0.4,
 69317: 0.8,
 70453: 0.16,
 52233: 0.32,
 63368: 0.14545454545454545,
 66842: 2.0,
 337928: 0.07

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [75]:
mask = np.argsort(data[:,1])
data9 = data[mask][::-1]
np.mean(data9[:100, 2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [85]:
#data[np.random.choice(data[:,0], 10)]
data[np.random.choice(data.shape[0], 10)]

array([[125040,     30,     10],
       [173165,    150,     11],
       [ 95769,     85,     10],
       [311609,     10,      7],
       [204703,     50,     11],
       [  9427,     60,      9],
       [ 91712,     65,      6],
       [ 23538,    105,     14],
       [335136,     20,      4],
       [ 95996,     40,     13]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [104]:
sr = np.mean(data[:, 2]) 
mask = data[:, 2] <= sr
data[mask, 2].size / data[:, 2].size * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [102]:
mask = (data[:, 1] <= 20) & (data[:, 2] <= 5)
data12 = np.c_[data, mask]
data12

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [105]:
mask = data12[:, 3] == 1
data12[mask, 3].size / data12[:, 2].size * 100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [133]:
short = data12[data12[:, 1] < 10]
standart = data12[(data12[:, 1] >= 10) & (data12[:, 1] < 20)]
long = data12[data12[:, 1] >= 20]
k = np.min([short.shape[0], standart.shape[0], long.shape[0]])
data14 = np.array([short[:k], standart[:k], long[:k]])
data14 

array([[[ 67660,      5,      6,      0],
        [366174,      7,      9,      0],
        [204134,      5,      3,      1],
        ...,
        [420725,      5,      3,      1],
        [  4747,      0,      9,      0],
        [370915,      5,      4,      1]],

       [[ 94746,     10,      6,      0],
        [ 33941,     18,      9,      0],
        [446597,     15,      5,      1],
        ...,
        [  9831,     15,      7,      0],
        [335859,     12,     14,      0],
        [256812,     10,      3,      1]],

       [[127244,     60,     16,      0],
        [ 23891,     25,      7,      0],
        [157911,     60,     14,      0],
        ...,
        [168901,     25,      7,      0],
        [392339,     35,     13,      0],
        [206732,     45,     10,      0]]])